[target.x86_64-pc-windows-gnu]
linker = "rust-lld"
rustflags = ["-C", "link-self-contained=yes"]

[target.wasm32-unknown-unknown]
linker = "rust-lld"
rustflags = ["-C", "link-self-contained=yes"]

[build]
jobs = 4
